### ISSUE TITLE
Equidistant path generation results in invalid path

### ISSUE THREAD

**Issue by pasmat** [margitantal68/sapiagent#1]
I was toying around with the code, but couldn't get it to run succesfully

The create_equidistant_actions.py's function create_actions, code is supposed to create a equidistant path between two points, but for the path provided on the graphs in the paper as an example between {x: 1180, y: 255} to {x: 1230: y: 275} produces an path from {x: 1180, y: 255} to {x: 1230: y: 255}, as the code in create_actions floors the dx / dy that is used to generate the path and even if the length of the path is adjusted, it will never be able to generate a path from {x: 1180, y: 255} to {x: 1230: y: 275} as the dx / dy are truncated

`    dx = floor((x2 - x1) / n)
    dy = floor((y2 - y1) / n)`

So if the path isn't exactly proportional, the generated path will never reach the end point

Is this intentional and is there a reason why its truncated?

Here's the code I tried to create a path with
[create_path.py](https://gist.github.com/pasmat/4e5000b5696fe882b6a0a6a1ee35d6f1)
[refactored the create_equidistant_actions.py to expose the path creation function](https://gist.github.com/pasmat/3863a167f0ac7c527b11c3e4b88d75af)

And the paths created doesn't seem to be anything like in the paper

Here's an example path generated from  {x: 1180, y: 255} to {x: 1230: y: 275}

`1180.0,255.0
1180.0,256.0
1181.0,256.0
1182.0,256.0
1183.0,256.0
1184.0,255.0
1185.0,254.0
1185.0,253.0
1186.0,252.0
1187.0,251.0
1188.0,251.0
1189.0,251.0
1189.0,251.0
1189.0,250.0
1189.0,249.0
1189.0,248.0`

[https://i.imgur.com/4xpJCBC.png](plotted path)

I followed the steps described in readme

Thank you for your time and for this great paper.

**Comment by margitantal68** [comment]
Thank you for your message. Indeed, it was an error, but it is now
corrected.
Truncation is needed as the output should be a sequence of integers, as the
mouse movement is considered to be on the screen (integer screen
coordinates).
import numpy as np
import matplotlib.pyplot as plt


# (x1, y1) - start point
# (x2, y2) - end point
# n - number of segments (offsets)
def create_actions(x1, y1, x2, y2, n):
print("(", x1, ",", y1, ") - ", "(", x2, ",", y2, ")")
dx = (x2 - x1) / n
dy = (y2 - y1) / n

x = []
y = []
for i in range(0, n + 1):
x.append(x1 + i * dx)
y.append(y1 + i * dy)

x_int = [int(a) for a in x]
y_int = [int(a) for a in y]

dx_list = np.diff(x_int)
dy_list = np.diff(y_int)

plt.plot(x, y, marker="s")
plt.plot(x_int, y_int, marker="x")
plt.savefig("line.png")


create_actions(914, 370, 1200, 600, 51)

pasmat ***@***.***> ezt írta (időpont: 2022. ápr. 15., P,
0:10):

**Comment by pasmat** [comment]
Ah - Amazing, thank you!

I pulled the new code, and the equidistant generated line is now as expected

After training the model again now with the new code, with fcn supervised learning and with the sapimouse dataset, and using the same code from the initial issue to generate a mouse path with the model, the model doesn't seem to generate similar features to the paper

Here's a visualization of the path I generated with my code from first issue vs. the one from paper https://i.imgur.com/lOxnnqd.jpg

Is there something obvious I am doing wrong, or something I could try?

Thank you so much

**Comment by margitantal68** [comment]
Figure 5. shows the main idea of the autoencoder training: the input and
the expected output, it does not show any generated trajectories.

Attached you will find the detailed image of the original trajectory shown
in Fig. 5 and the generated trajectories with conventional (unsupervised)
and our approach (supervised) learning (temp7_unsupervised.png,
temp7_supervised.png).
Unfortunately, I am very busy and do not have time to retrain the models.
As soon as I have the new trajectories I'll let you know.

pasmat ***@***.***> ezt írta (időpont: 2022. ápr. 15., P,
13:46):

**Comment by pasmat** [comment]
Ah, thank you.

Unfortunately, Github striped the attached images from the e-mail, so I can't see them.

I understand your busyness and appreciate your time highly.

Looking forward for the trajectories, and meanwhile I try with my limited knowledge to see if I can figure it out on my own.

Thank you, again!

**Comment by margitantal68** [comment]
Send me your email address, and I will send the attached images.

pasmat ***@***.***> ezt írta (időpont: 2022. ápr. 15., P,
15:51):

**Comment by pasmat** [comment]
[redacted] - thanks
